services:
  mqtt:
    image: eclipse-mosquitto:2
    container_name: telemetry-mqtt
    ports:
      - "1883:1883"     # MQTT
    volumes:
      - ./mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
