services:
  mqtt:
    image: eclipse-mosquitto:2
    container_name: telemetry-mqtt
    ports:
      - "1883:1883"     # MQTT
    volumes:
      - ./mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro

  db:
    image: postgres:17
    container_name: telemetry-postgres
    environment:
      POSTGRES_DB: telemetry
      POSTGRES_USER: telemetry
      POSTGRES_PASSWORD: telemetry_dev
    ports:
      - "5434:5432"
    volumes:
      - telemetry-pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U telemetry"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  telemetry-pgdata:
